language: cpp

env:
  - CMAKE_VERSION=3.2 CMAKE_REV=3
  - CMAKE_VERSION=3.1 CMAKE_REV=3

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
  - sudo apt-get install qt5-default qttools5-dev qttools5-dev-tools
  - sudo apt-get install yasm
  - sudo apt-get install libboost-dev

install:
  -    wget http://www.cmake.org/files/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}.${CMAKE_REV}-Linux-x86_64.sh
    && sudo sh cmake-${CMAKE_VERSION}.${CMAKE_REV}-Linux-x86_64.sh --skip-license --prefix=/usr
    && cmake --version

compiler:
  - clang
  - gcc

script: python test.py --work_dir /tmp/consort-cmake -D CONSORT_PERMIT_NFS_BUILDS=ON -D QT_ROOT=/usr -D QT_LIBRARYDIR=/usr/lib/x86_64-linux-gnu
