language: cpp

install:
  -    wget http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-i386.tar.gz
    && tar -xzf cmake-3.2.3-Linux-i386.tar.gz
    && sudo cp -fR cmake-3.2.3-Linux-i386/* /usr
    && hash -r
    && which cmake
    && cmake --version

compiler:
  - clang
  - gcc

script: pwd && which cmake && cmake --version && python test.py
