language: cpp

env:
  - CMAKE_VERSION=3.2 CMAKE_REV=3
  - CMAKE_VERSION=3.1 CMAKE_REV=3

install:
  -    wget http://www.cmake.org/files/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}.${CMAKE_REV}-Linux-x86_64.sh
    && sudo sh cmake-${CMAKE_VERSION}.${CMAKE_REV}-Linux-x86_64.sh --skip-license --prefix=/usr
    && cmake --version

compiler:
  - clang
  - gcc

script: python test.py
