# This file teaches CMake how to build with YASM.

set(CMAKE_ASM_YASM_SOURCE_FILE_EXTENSIONS asm)

if(NOT CMAKE_ASM_YASM_OBJECT_FORMAT)
	if(CONSORT_WINDOWS_X86_64)
		set(CMAKE_ASM_YASM_OBJECT_FORMAT win64)
	elseif(CONSORT_WINDOWS_X86)
		set(CMAKE_ASM_YASM_OBJECT_FORMAT win32)
	elseif(CONSORT_MACOSX_X86_64)
		set(CMAKE_ASM_YASM_OBJECT_FORMAT macho64)
	elseif(CONSORT_MACOSX_X86)
		set(CMAKE_ASM_YASM_OBJECT_FORMAT macho)
	elseif(CONSORT_LINUX_X86_64)
		set(CMAKE_ASM_YASM_OBJECT_FORMAT elf64)
	elseif(CONSORT_LINUX_X86)
		set(CMAKE_ASM_YASM_OBJECT_FORMAT elf)
	endif()
endif()

if(NOT CMAKE_ASM_YASM_COMPILE_OBJECT)
	set(CMAKE_ASM_YASM_COMPILE_OBJECT "<CMAKE_ASM_YASM_COMPILER> -f ${CMAKE_ASM_YASM_OBJECT_FORMAT} <FLAGS> <DEFINES> -o <OBJECT> <SOURCE>")
endif()

# Load the generic ASMInformation file:
set(ASM_DIALECT "_YASM")
include(CMakeASMInformation)
set(ASM_DIALECT)
